services:
  app:
    image: ghcr.io/nwerosama/daggerbot-rs:koi
    environment:
      DOCKER_HOSTNAME: '{{ .Node.Hostname }}'
      MONICA_GRPC_URI: '192.168.70.225:37090'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
      labels:
        - traefik.enable=false
