apiVersion: apps/v1
kind: Deployment
metadata:
  name: daggerbot

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: daggerbot
  template:
    metadata:
      labels:
        app: daggerbot
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: daggerbot-app
          image: ghcr.io/nwerosama/daggerbot-rs:koi
          imagePullPolicy: Always
          env:
            - name: DOCKER_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MONICA_GRPC_URI
              valueFrom:
                secretKeyRef:
                  name: daggerbot-secret
                  key: MONICA_GRPC_URI
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "64Mi"
            limits:
              cpu: "2000m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: daggerbot-service

spec:
  selector:
    app: daggerbot
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      name: health
