name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: '${{ secrets.NWERO_PAT }}'

      - name: APT Cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libprotobuf-dev libprotobuf32t64 libprotoc32t64 protobuf-compiler
          version: 1.0

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cache-v1
          cache-on-failure: 'true'
          cache-all-crates: 'true'

      - name: Install Rust components
        run: rustup component add rustfmt clippy

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --locked --all-features
